<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FilmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('film')->truncate();
        
        DB::table('film')->insert([
            ['filmcim' => 'Ágnes öcsénk', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'német', 'mufaj' => 'dráma', 'hossz' => 115],
            ['filmcim' => 'Az állomásfőnök', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'dráma', 'hossz' => 88],
            ['filmcim' => 'Álmodozók', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol-francia-olasz', 'mufaj' => 'dráma', 'hossz' => 110],
            ['filmcim' => 'Amelie csodálatos élete', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'francia-német', 'mufaj' => 'vígjáték', 'hossz' => 117],
            ['filmcim' => 'Annie Hall', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 89],
            ['filmcim' => 'Anyám a lányokat szereti', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'spanyol', 'mufaj' => 'vígjáték', 'hossz' => 96],
            ['filmcim' => 'Anyátlanok', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'japán', 'mufaj' => 'játékfilm', 'hossz' => 141],
            ['filmcim' => 'Apokalipszis most - rendezői változat', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'dráma', 'hossz' => 202],
            ['filmcim' => 'Apokalipszis most I-II;', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'dráma', 'hossz' => 159],
            ['filmcim' => 'Arizonai álmodozók', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'dráma', 'hossz' => 135],
            ['filmcim' => 'Bábok', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'japán', 'mufaj' => 'dráma', 'hossz' => 109],
            ['filmcim' => 'Beszélj hozzá!', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'spanyol', 'mufaj' => 'dráma', 'hossz' => 109],
            ['filmcim' => 'Bin-jip - Lopakodó lelkek', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'dél-koreai-japán', 'mufaj' => 'dráma', 'hossz' => 88],
            ['filmcim' => 'A bíró és a hóhér', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'NSZK-olasz', 'mufaj' => 'krimi', 'hossz' => 90],
            ['filmcim' => 'Broken Flowers - Hervadó virágok', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai-francia', 'mufaj' => 'vígjáték', 'hossz' => 105],
            ['filmcim' => 'A bűvös körhinta', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'francia', 'mufaj' => 'animációs', 'hossz' => 85],
            ['filmcim' => 'Cápasrác és Lávalány kalandjai', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'kalandfilm', 'hossz' => 112],
            ['filmcim' => 'Charlie és a csokigyár', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai-angol', 'mufaj' => 'vígjáték', 'hossz' => 106],
            ['filmcim' => 'Che Guevara: A motoros naplója', 'szines' => false, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai-angol-argentin-német', 'mufaj' => 'dráma', 'hossz' => 128],
            ['filmcim' => 'Csak szex és más semmi', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 93],
            ['filmcim' => 'Csodacsibe', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'animációs', 'hossz' => 77],
            ['filmcim' => 'Csodálatos Júlia', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'kanadai', 'mufaj' => '', 'hossz' => 104],
            ['filmcim' => 'Datolya', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'belga-francia-tunéziai', 'mufaj' => '', 'hossz' => 82],
            ['filmcim' => 'Dig! - Ezt kapd ki!', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'dokumentum', 'hossz' => 107],
            ['filmcim' => 'A diktátor', 'szines' => false, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'filmszatíra', 'hossz' => 120],
            ['filmcim' => 'Dogville - A menedék', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'dán-svéd-norvég-német-finn-olasz-japán-angol-amerikai', 'mufaj' => 'dráma', 'hossz' => 177],
            ['filmcim' => 'Domino', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia-amerikai', 'mufaj' => 'akció', 'hossz' => 127],
            ['filmcim' => 'Durr, durr és csók', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'thriller', 'hossz' => 103],
            ['filmcim' => 'Edukators', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'német-osztrák', 'mufaj' => 'játékfilm', 'hossz' => 127],
            ['filmcim' => 'Egy cipőben', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 130],
            ['filmcim' => 'Egy hulla, egy falafel és a többiek…', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'ausztrál-olasz', 'mufaj' => 'vígjáték', 'hossz' => 107],
            ['filmcim' => 'Egy szoknya, egy nadrág', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 95],
            ['filmcim' => 'Elveszett jelentés', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai-japán', 'mufaj' => 'dráma', 'hossz' => 102],
            ['filmcim' => 'Én, Pán Péter', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol-amerikai', 'mufaj' => 'dráma', 'hossz' => 106],
            ['filmcim' => 'Eros', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai-olasz-hongkongi-kínai-francia-luxemburgi-angol', 'mufaj' => 'dráma', 'hossz' => 104],
            ['filmcim' => 'Fej vagy írás', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 90],
            ['filmcim' => 'Fekete Kefe', 'szines' => false, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 80],
            ['filmcim' => 'A fény ösvényei', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'dráma', 'hossz' => 89],
            ['filmcim' => 'Futball faktor', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol', 'mufaj' => 'dráma', 'hossz' => 91],
            ['filmcim' => 'Fűrész 2', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'thriller', 'hossz' => 93],
            ['filmcim' => 'Galaxis útikalauz stopposoknak', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai-angol', 'mufaj' => 'vígjáték', 'hossz' => 110],
            ['filmcim' => 'Garfield', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 81],
            ['filmcim' => 'Genezis', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'francia-olasz', 'mufaj' => 'természetfilm', 'hossz' => 81],
            ['filmcim' => 'Getno', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'játékfilm', 'hossz' => 95],
            ['filmcim' => 'Grimm', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'cseh-amerikai', 'mufaj' => 'fantasy', 'hossz' => 118],
            ['filmcim' => 'Ha igaz volna…', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 95],
            ['filmcim' => 'A halott menyasszony', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol', 'mufaj' => 'animációs', 'hossz' => 78],
            ['filmcim' => 'Harry Potter és a Tűz Serlege', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'fantasy', 'hossz' => 157],
            ['filmcim' => 'Hawaii, Oslo', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'dán-svéd-norvég', 'mufaj' => 'dráma', 'hossz' => 125],
            ['filmcim' => 'A hetedik nap', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'spanyol', 'mufaj' => 'dráma', 'hossz' => 103],
            ['filmcim' => 'Hétköznapi mennyország', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'svéd', 'mufaj' => 'dráma', 'hossz' => 130],
            ['filmcim' => 'Híd a Kwai folyón', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'angol-amerikai', 'mufaj' => 'dráma', 'hossz' => 161],
            ['filmcim' => 'Hideg csontok', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'spanyol', 'mufaj' => 'thriller', 'hossz' => 100],
            ['filmcim' => 'Holdfényév', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'dráma', 'hossz' => 117],
            ['filmcim' => 'Hölgyek levendulában', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol', 'mufaj' => 'dráma', 'hossz' => 103],
            ['filmcim' => 'Hős', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'hongkongi', 'mufaj' => '', 'hossz' => 96],
            ['filmcim' => 'A hősök nem pihennek', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'francia-osztrák', 'mufaj' => 'dráma', 'hossz' => 104],
            ['filmcim' => 'Human Traffic', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'angol-ír', 'mufaj' => 'vígjáték', 'hossz' => 99],
            ['filmcim' => 'Hurrá, nyaralunk!', 'szines' => false, 'szinkron' => 'szinkronizált', 'szarmazas' => 'szovjet', 'mufaj' => 'ifjúsági', 'hossz' => 74],
            ['filmcim' => 'Az igazi Mikulás', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'játékfilm', 'hossz' => 90],
            ['filmcim' => 'Az igazság fogságában', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'kanadai', 'mufaj' => '', 'hossz' => 108],
            ['filmcim' => 'Az ígéret - Fényes nappal történt', 'szines' => false, 'szinkron' => 'feliratos', 'szarmazas' => 'NSZK-svájci-spanyol', 'mufaj' => 'krimi', 'hossz' => 90],
            ['filmcim' => 'Az ígéret megszállottja', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'dráma', 'hossz' => 124],
            ['filmcim' => 'Intimitás', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'francia-angol-német-spanyol', 'mufaj' => 'dráma', 'hossz' => 115],
            ['filmcim' => 'Isten városa', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'brazil-francia', 'mufaj' => 'dráma', 'hossz' => 130],
            ['filmcim' => 'Játszik még a szív', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol', 'mufaj' => 'vígjáték', 'hossz' => 100],
            ['filmcim' => 'Johanna', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'operafilm', 'hossz' => 90],
            ['filmcim' => 'Kairó bíbor rózsája', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 84],
            ['filmcim' => 'Kávé és cigaretta', 'szines' => false, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'zenés', 'hossz' => 95],
            ['filmcim' => 'Kész cirkusz', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 74],
            ['filmcim' => 'A kilencedik nap', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'német-luxemburgi', 'mufaj' => 'dráma', 'hossz' => 98],
            ['filmcim' => 'King Kong', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'új-zélandi', 'mufaj' => '', 'hossz' => 188],
            ['filmcim' => 'Kontroll', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'thriller', 'hossz' => 102],
            ['filmcim' => 'Kőkemény család', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 104],
            ['filmcim' => 'A közvetítő', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'dokumentum', 'hossz' => 89],
            ['filmcim' => 'Kulcsár & Haverok', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => '', 'hossz' => 80],
            ['filmcim' => 'Kutyaszorítóban', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'thriller', 'hossz' => 99],
            ['filmcim' => 'Kutyátlanok kíméljenek', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 98],
            ['filmcim' => 'Lakótársat keresünk', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia-spanyol', 'mufaj' => 'vígjáték', 'hossz' => 120],
            ['filmcim' => 'Leány gyöngy fülbevalóval', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol-luxemburgi', 'mufaj' => 'dráma', 'hossz' => 95],
            ['filmcim' => 'Légcsavar', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'thriller', 'hossz' => 98],
            ['filmcim' => 'A legtöbb ember Kínában él…', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'norvég', 'mufaj' => 'dráma', 'hossz' => 82],
            ['filmcim' => 'Lélektől lélekig', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia-dél-afrikai-angol', 'mufaj' => 'kalandfilm', 'hossz' => 122],
            ['filmcim' => 'Madagaszkár', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'animációs', 'hossz' => 80],
            ['filmcim' => 'Magyar vándor', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 110],
            ['filmcim' => 'Manderlay', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'dán-svéd-francia-német-amerikai', 'mufaj' => 'dráma', 'hossz' => 139],
            ['filmcim' => 'Manhattan', 'szines' => false, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 96],
            ['filmcim' => 'Maszájok', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia', 'mufaj' => 'dráma', 'hossz' => 94],
            ['filmcim' => 'Még mindig lakótársat keresünk', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia-angol', 'mufaj' => 'vígjáték', 'hossz' => 125],
            ['filmcim' => 'Melinda és Melinda', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'vígjáték', 'hossz' => 100],
            ['filmcim' => 'Mennyország most', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia-német-holland-izrael', 'mufaj' => '', 'hossz' => 90],
            ['filmcim' => 'Mezítlábas szerelem', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'német', 'mufaj' => 'vígjáték', 'hossz' => 110],
            ['filmcim' => 'Mi a csudát tudunk a világról?', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'játékfilm', 'hossz' => 108],
            ['filmcim' => 'Mint egy angyal', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia-olasz', 'mufaj' => 'dráma', 'hossz' => 110],
            ['filmcim' => 'Monsieur Ibrahim és a Korán virágai', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia-török', 'mufaj' => 'dráma', 'hossz' => 94],
            ['filmcim' => 'Naqoyqatsi - Erőszakos világ', 'szines' => true, 'szinkron' => 'szöveg nélküli', 'szarmazas' => 'amerikai', 'mufaj' => 'filmesszé', 'hossz' => 89],
            ['filmcim' => 'Narnia Krónikái - Az oroszlán, a boszorkány és a ruhásszekrény', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai-új-zélandi', 'mufaj' => 'fantasy', 'hossz' => 140],
            ['filmcim' => 'Nesze neked, Pete Tong!', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol-kanadai', 'mufaj' => 'vígjáték', 'hossz' => 90],
            ['filmcim' => 'Nézz balra, ott egy svéd!', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'dán', 'mufaj' => 'vígjáték', 'hossz' => 90],
            ['filmcim' => 'Nyomorultak', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'francia-olasz-NDK', 'mufaj' => 'dráma', 'hossz' => 225],
            ['filmcim' => 'Oldboy', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'dél-koreai', 'mufaj' => 'thriller', 'hossz' => 120],
            ['filmcim' => 'Az operaház fantomja', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'amerikai', 'mufaj' => 'musical', 'hossz' => 92],
            ['filmcim' => 'Ördögűzés Emily Rose üdvéért', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'horror', 'hossz' => 119],
            ['filmcim' => 'Pata-csata', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'dél-afrikai-amerikai', 'mufaj' => 'vígjáték', 'hossz' => 94],
            ['filmcim' => 'Pingvinek vándorlása', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'francia', 'mufaj' => 'dokumentum', 'hossz' => 85],
            ['filmcim' => 'A pityergő teve története', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'német-mongol', 'mufaj' => 'dokumentum', 'hossz' => 87],
            ['filmcim' => 'Ponyvaregény - Pulp Fiction', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'filmszatíra', 'hossz' => 150],
            ['filmcim' => 'Porcelánbaba', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'dráma', 'hossz' => 74],
            ['filmcim' => 'Rap, Revü, Rómeó', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 82],
            ['filmcim' => 'A Rashevski tangó', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'belga-luxemburgi-francia', 'mufaj' => '', 'hossz' => 90],
            ['filmcim' => 'Rekonstrukció', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'dán', 'mufaj' => 'dráma', 'hossz' => 88],
            ['filmcim' => 'A repülő tőrök klánja', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'kínai-hongkongi', 'mufaj' => 'akció', 'hossz' => 111],
            ['filmcim' => 'A rövidek éjszakája', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia-angol-spanyol-dán', 'mufaj' => 'rövidfilm', 'hossz' => 68],
            ['filmcim' => 'Segítség, hal lettem!', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'dán-ír-német', 'mufaj' => 'animációs', 'hossz' => 80],
            ['filmcim' => 'Senki nem tud semmit', 'szines' => false, 'szinkron' => 'szinkronizált', 'szarmazas' => 'csehszlovák', 'mufaj' => 'vígjáték', 'hossz' => 70],
            ['filmcim' => 'Sin City', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'akció', 'hossz' => 124],
            ['filmcim' => 'Sóhajtenger - Kuba', 'szines' => false, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'rövidfilm', 'hossz' => 5],
            ['filmcim' => 'Egy sorozatgyilkos nyara', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'dráma', 'hossz' => 136],
            ['filmcim' => 'A sötétség útja - Mulholland Drive', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai-francia', 'mufaj' => 'dráma', 'hossz' => 141],
            ['filmcim' => 'Stalker', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'szovjet-NSZK', 'mufaj' => 'sci-fi', 'hossz' => 160],
            ['filmcim' => 'Super Size Me', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'dokumentum', 'hossz' => 96],
            ['filmcim' => 'Szamszára', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'indiai-német-francia-olasz', 'mufaj' => 'dráma', 'hossz' => 140],
            ['filmcim' => 'Szent Lajos király hídja', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'spanyol', 'mufaj' => '', 'hossz' => 120],
            ['filmcim' => 'A szenvedélyek labirintusa', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'spanyol', 'mufaj' => 'játékfilm', 'hossz' => 100],
            ['filmcim' => 'Szerelmem nyara', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol', 'mufaj' => 'dráma', 'hossz' => 86],
            ['filmcim' => 'Szeress, ha mersz', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'francia-belga', 'mufaj' => '', 'hossz' => 93],
            ['filmcim' => 'Szex, szerelem, olaszok', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'olasz-svájci-angol', 'mufaj' => 'vígjáték', 'hossz' => 125],
            ['filmcim' => 'Szőke Kóla', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 96],
            ['filmcim' => 'Szürke, Mercivel', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'jugoszláv-német-szlovén-szerb', 'mufaj' => 'vígjáték', 'hossz' => 95],
            ['filmcim' => 'Szürkület', 'szines' => false, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'krimi', 'hossz' => 105],
            ['filmcim' => 'Táncos a sötétben', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'dán-svéd-francia', 'mufaj' => 'dráma', 'hossz' => 134],
            ['filmcim' => 'Tangó és tulipán', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'olasz-svájci', 'mufaj' => 'vígjáték', 'hossz' => 112],
            ['filmcim' => 'Tapló télapó', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai-német', 'mufaj' => 'vígjáték', 'hossz' => 98],
            ['filmcim' => 'Tavasz, Nyár, Ősz, Tél és Tavasz', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'dél-koreai-német', 'mufaj' => 'dráma', 'hossz' => 99],
            ['filmcim' => 'Tavasz van', 'szines' => false, 'szinkron' => 'feliratos', 'szarmazas' => 'olasz', 'mufaj' => 'dráma', 'hossz' => 90],
            ['filmcim' => 'Twist Olivér', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'angol-cseh-francia-olasz', 'mufaj' => 'dráma', 'hossz' => 130],
            ['filmcim' => 'Utazások egy szerzetessel', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'dokumentum', 'hossz' => 65],
            ['filmcim' => 'Ütközések', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai-német', 'mufaj' => 'dráma', 'hossz' => 113],
            ['filmcim' => 'Üvegfal', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'játékfilm', 'hossz' => 87],
            ['filmcim' => 'Üvegtigris', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'vígjáték', 'hossz' => 100],
            ['filmcim' => 'Vad galamb', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'angol', 'mufaj' => 'animációs', 'hossz' => 76],
            ['filmcim' => 'A vágy törvénye', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'spanyol', 'mufaj' => 'dráma', 'hossz' => 102],
            ['filmcim' => 'Van élet a halál előtt?', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'dokumentum', 'hossz' => 110],
            ['filmcim' => 'A vándorló palota', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'japán', 'mufaj' => 'animációs', 'hossz' => 119],
            ['filmcim' => 'Vera Drake', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'angol-francia-új-zélandi', 'mufaj' => 'dráma', 'hossz' => 124],
            ['filmcim' => 'Világok arca: Baraka', 'szines' => true, 'szinkron' => 'szöveg nélküli', 'szarmazas' => 'amerikai', 'mufaj' => 'dokumentum', 'hossz' => 96],
            ['filmcim' => 'Vincent, François, Paul és a többiek', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'francia-olasz', 'mufaj' => 'dráma', 'hossz' => 120],
            ['filmcim' => 'Vízcseppek a forró kövön', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia', 'mufaj' => 'dráma', 'hossz' => 90],
            ['filmcim' => 'Vuk', 'szines' => true, 'szinkron' => 'nincs adat', 'szarmazas' => 'magyar', 'mufaj' => 'rajzfilm', 'hossz' => 74],
            ['filmcim' => 'Wallace & Gromit és az Elvetemült Veteménylény', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'angol', 'mufaj' => 'animációs', 'hossz' => 94],
            ['filmcim' => 'Waterloo Bridge', 'szines' => false, 'szinkron' => 'feliratos', 'szarmazas' => 'amerikai', 'mufaj' => 'dráma', 'hossz' => 103],
            ['filmcim' => 'Whisky', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'uruguayi-argentin-német-spanyol', 'mufaj' => 'komédia', 'hossz' => 99],
            ['filmcim' => 'Zorro legendája', 'szines' => true, 'szinkron' => 'szinkronizált', 'szarmazas' => 'amerikai', 'mufaj' => 'kalandfilm', 'hossz' => 131],
            ['filmcim' => '5x2', 'szines' => true, 'szinkron' => 'feliratos', 'szarmazas' => 'francia', 'mufaj' => 'dráma', 'hossz' => 90],
        ]);
    }
}
